### PR TITLE
Fix widths for columns with extra lines

### PR DESCRIPTION
**Pull request by mrgregory**
This is my quick fix for ascii table renderer.
Columns hadn't got proper widths for extra lines.

### CODE REVIEW

**Comment by danielbachhuber** [comment]
Can you provide some context as to what this is fixing, and add tests?

**Comment by mrgregory** [comment]
In the lib/cli/table/Ascii.php line 145 you fill the $extra_row array by associative keys, but on the line 129 you filled by indexes. 
the result:
<pre>
| A | A2 | A3 with l |
| | | ong text |
| B | B2 | B3        |
| C | C2 | C3        |
</pre>
I fill the $extra_row array by associative keys inside the foreach, and the result:
<pre>
| A | A2 | A3 with l |
|   |    | ong text  |
| B | B2 | B3        |
| C | C2 | C3        |
</pre>
And sorry, I don't know how can I test this case.

**Comment by mrgregory** [comment]
I added test for it, but it will works with 120 width console, because it depends on `tput cols` command

**Comment by mrgregory** [comment]
I found the default value in Shell.php :-) It was 80 cols

**Comment by mrgregory** [comment]
Will you accept it or do you need any other information?

**Comment by danielbachhuber** [comment]
> Will you accept it or do you need any other information?

Sorry I missed this earlier. Could we mock the value of `tput cols` in the test, so it's not unnecessarily dependent on the environment? The tests fail locally for me, and I can see this becoming a pain point.

**Comment by mrgregory** [comment]
I found the solution for `tput cols`, a default value 80 defined for columns if there isn't in the environment and I sent it with my last commit.

**Comment by danielbachhuber** [comment]
> a default value 80 defined for columns if there isn't in the environment and I sent it with my last commit.

Right, but when `tput cols` is set, like my local environment, the tests will fail:

```
salty-wordpress ➜  php-cli-tools  phpunit
PHPUnit 4.4.1 by Sebastian Bergmann.

Configuration read from /home/vagrant/.wp-cli/vendor/wp-cli/php-cli-tools/phpunit.xml

.........................F.

Time: 270 ms, Memory: 4.50Mb

There was 1 failure:

1) Test_Table_Ascii::testDrawWithMultilineCell
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'+----+----+-------------------------------------------------------------------------------------------------------------------+
-| 1  | 2  | 3                                                                                                                 |
-+----+----+-------------------------------------------------------------------------------------------------------------------+
-| A1 | A2 | A3 with long text with long text with long text with long text with long text with long text with long text with  |
-|    |    | long text with long text with long text with long text                                                            |
-| B1 | B2 | B3                                                                                                                |
-| C1 | C2 | C3                                                                                                                |
-+----+----+-------------------------------------------------------------------------------------------------------------------+
+'+----+----+-------------------------------------------------------------------+
+| 1  | 2  | 3                                                                 |
++----+----+-------------------------------------------------------------------+
+| A1 | A2 | A3 with long text with long text with long text with long text wi |
+|    |    | th long text with long text with long text with long text with lo |
+|    |    | ng text with long text with long text                             |
+| B1 | B2 | B3                                                                |
+| C1 | C2 | C3                                                                |
++----+----+-------------------------------------------------------------------+
 '

/home/vagrant/.wp-cli/vendor/wp-cli/php-cli-tools/tests/test-table-ascii.php:234
/home/vagrant/.wp-cli/vendor/wp-cli/php-cli-tools/tests/test-table-ascii.php:225
/home/vagrant/.wp-cli/vendor/wp-cli/php-cli-tools/tests/test-table-ascii.php:211

FAILURES!
Tests: 27, Assertions: 70, Failures: 1.
```

We should mock column width in tests to ensure a consistent environment.

**Pull request closed without merging**
