### PR TITLE
Escape % characters in table output properly. Fixes #86

### LINKED ISSUE #86: % characters not properly escaped before being passed to sprintf()
Using WP CLI, the following steps show the problem:

* Update your user account so that your name contains a %, e.g. "Lee %s Willis"
* Run wp user list
* Expected output:
```
+----+-------------+---------------+---------------------+---------------------+---------------+
| ID | user_login  | display_name  | user_email          | user_registered     | roles         |
+----+-------------+---------------+---------------------+---------------------+---------------+
| 5  | leewillis77 | Lee %s Willis | lee@example.com | 2015-07-19 15:11:01 | subscriber    |
```

* Actual output
```
+----+-------------+---------------+---------------------+---------------------+---------------+
| ID | user_login  | display_name  | user_email          | user_registered     | roles         |
+----+-------------+---------------+---------------------+---------------------+---------------+
| 5  | leewillis77 | Lee  Willis | lee@example.com | 2015-07-19 15:11:01 | subscriber    |
```

* Note that the name of the user is displayed as "Lee Willis".

The %s has not been escaped and has been passed to sprintf as-is. There is code already in place that looks like it tries to handle this, but it doesn't. 

PR to follow that simplifies the escaping (and resolves this issue), obviously it'll need review to see why the original wasn't this straightforward.

### PR DESCRIPTION
**Pull request by leewillis77**

### CODE REVIEW

**Comment by danielbachhuber** [comment]
Is it possible to add some test coverage for this?

**Comment by leewillis77** [comment]
Hi Daniel; 

Happy to look at that. Are you looking for test coverage in wp-cli - or in php-cli-tools? I'm struggling to work out where the tests would be - test-table-ascii.php looks like the closest candidate, but I'm not sure that it's doing the same thing as WP-CLI does - at least my tests (See updated PR) aren't doing what I'd expect.

**Comment by danielbachhuber** [comment]
> Are you looking for test coverage in wp-cli - or in php-cli-tools?

php-cli-tools

>  I'm struggling to work out where the tests would be

You're welcome to create a new file for it.

**Comment by danielbachhuber** [comment]
Closing in favor of #91

**Pull request closed without merging**
