### PR TITLE
Fix unit tests

### PR DESCRIPTION
**Pull request by swissspidy**
Trying to fix tests after https://github.com/wp-cli/wp-cli-tests/pull/206

I realized we were not actually running tests against PHP 5.3, only 5.6+, so I figured we can just bump the requirement while at it.

To-do:

* [ ] Figure out why tests are failing on CI, the autoloader doesn't seem to be working anymore... 🤔 Any help appreciated!

### CODE REVIEW

**Comment by thelovekesh** [comment]
@swissspidy It seems like on local, tests autoloading has no effect. Tests are running on local even when I disable this line

https://github.com/wp-cli/php-cli-tools/blob/283a9da6866fe4c7d496baf9f2b859702c617fd3/tests/bootstrap.php#L22

**Comment by thelovekesh** [comment]
Can I send some tests commits to this PR?

**Comment by swissspidy** [comment]
Yes I noticed that too, but no idea why.

And the error message on CI don't seem to make sense either

```
PHP Warning:  Uncaught require(/home/runner/work/php-cli-tools/php-cli-tools/lib/cli/Table/Ascii.php): failed to open stream: No such file or directory

/home/runner/work/php-cli-tools/php-cli-tools/tests/bootstrap.php:19
```

`/lib/cli/Table/Ascii.php` _does_ exist

**Comment by thelovekesh** [comment]
Error message have `Table` in the path while the directory name is `table`.

**Comment by thelovekesh** [comment]
```
├── table
│   ├── Ascii.php
│   ├── Renderer.php
│   └── Tabular.php
```

**Comment by swissspidy** [comment]
That was it! Thanks @thelovekesh!

**Review by thelovekesh — APPROVED** [review]

**Comment by thelovekesh** [comment]
Still a mystery to me, why it was not reproducible on my local 🤔. I guess it has something to do with tests custom autoloader.

**Comment by swissspidy** [comment]
Case insensitive filesystem I suppose

**Pull request merged**
